/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReverifyRouteImport } from './routes/reverify'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MeRouteImport } from './routes/me'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as CardRouteImport } from './routes/card'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiddurIndexRouteImport } from './routes/siddur/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as BenefitsIndexRouteImport } from './routes/benefits/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SiddurIdRouteImport } from './routes/siddur/$id'
import { Route as GuidesIdRouteImport } from './routes/guides/$id'
import { Route as ExploreTransitRouteImport } from './routes/explore/transit'
import { Route as ExploreShopsRouteImport } from './routes/explore/shops'
import { Route as ExploreRidesRouteImport } from './routes/explore/rides'
import { Route as ExploreReserveRouteImport } from './routes/explore/reserve'
import { Route as ExploreHousingRouteImport } from './routes/explore/housing'
import { Route as ExploreHealthRouteImport } from './routes/explore/health'
import { Route as ExploreFoodRouteImport } from './routes/explore/food'
import { Route as ExploreEventsRouteImport } from './routes/explore/events'
import { Route as ExploreCommunityRouteImport } from './routes/explore/community'
import { Route as ExploreAdminRouteImport } from './routes/explore/admin'
import { Route as BenefitsIdRouteImport } from './routes/benefits/$id'
import { Route as AdminPromotionsRouteImport } from './routes/admin/promotions'
import { Route as AdminMoneyRouteImport } from './routes/admin/money'
import { Route as AdminMembershipsRouteImport } from './routes/admin/memberships'
import { Route as AdminControlsRouteImport } from './routes/admin/controls'
import { Route as AdminAppsRouteImport } from './routes/admin/apps'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ExploreServiceIdRouteImport } from './routes/explore/service.$id'
import { Route as ExploreCategoryIdRouteImport } from './routes/explore/category.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksAirwallexRouteImport } from './routes/api/public/webhooks/airwallex'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReverifyRoute = ReverifyRouteImport.update({
  id: '/reverify',
  path: '/reverify',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiddurIndexRoute = SiddurIndexRouteImport.update({
  id: '/siddur/',
  path: '/siddur/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsIndexRoute = BenefitsIndexRouteImport.update({
  id: '/benefits/',
  path: '/benefits/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SiddurIdRoute = SiddurIdRouteImport.update({
  id: '/siddur/$id',
  path: '/siddur/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIdRoute = GuidesIdRouteImport.update({
  id: '/guides/$id',
  path: '/guides/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreTransitRoute = ExploreTransitRouteImport.update({
  id: '/explore/transit',
  path: '/explore/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreShopsRoute = ExploreShopsRouteImport.update({
  id: '/explore/shops',
  path: '/explore/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRidesRoute = ExploreRidesRouteImport.update({
  id: '/explore/rides',
  path: '/explore/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreReserveRoute = ExploreReserveRouteImport.update({
  id: '/explore/reserve',
  path: '/explore/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreHousingRoute = ExploreHousingRouteImport.update({
  id: '/explore/housing',
  path: '/explore/housing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreHealthRoute = ExploreHealthRouteImport.update({
  id: '/explore/health',
  path: '/explore/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreFoodRoute = ExploreFoodRouteImport.update({
  id: '/explore/food',
  path: '/explore/food',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreEventsRoute = ExploreEventsRouteImport.update({
  id: '/explore/events',
  path: '/explore/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCommunityRoute = ExploreCommunityRouteImport.update({
  id: '/explore/community',
  path: '/explore/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreAdminRoute = ExploreAdminRouteImport.update({
  id: '/explore/admin',
  path: '/explore/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsIdRoute = BenefitsIdRouteImport.update({
  id: '/benefits/$id',
  path: '/benefits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMoneyRoute = AdminMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminControlsRoute = AdminControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppsRoute = AdminAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExploreServiceIdRoute = ExploreServiceIdRouteImport.update({
  id: '/explore/service/$id',
  path: '/explore/service/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCategoryIdRoute = ExploreCategoryIdRouteImport.update({
  id: '/explore/category/$id',
  path: '/explore/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksAirwallexRoute =
  ApiPublicWebhooksAirwallexRouteImport.update({
    id: '/api/public/webhooks/airwallex',
    path: '/api/public/webhooks/airwallex',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/exchange': typeof ExchangeRoute
  '/help': typeof HelpRoute
  '/mcp': typeof McpRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reverify': typeof ReverifyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/topup': typeof TopupRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/controls': typeof AdminControlsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/benefits/$id': typeof BenefitsIdRoute
  '/explore/admin': typeof ExploreAdminRoute
  '/explore/community': typeof ExploreCommunityRoute
  '/explore/events': typeof ExploreEventsRoute
  '/explore/food': typeof ExploreFoodRoute
  '/explore/health': typeof ExploreHealthRoute
  '/explore/housing': typeof ExploreHousingRoute
  '/explore/reserve': typeof ExploreReserveRoute
  '/explore/rides': typeof ExploreRidesRoute
  '/explore/shops': typeof ExploreShopsRoute
  '/explore/transit': typeof ExploreTransitRoute
  '/guides/$id': typeof GuidesIdRoute
  '/siddur/$id': typeof SiddurIdRoute
  '/admin/': typeof AdminIndexRoute
  '/benefits/': typeof BenefitsIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/siddur/': typeof SiddurIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/explore/category/$id': typeof ExploreCategoryIdRoute
  '/explore/service/$id': typeof ExploreServiceIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/airwallex': typeof ApiPublicWebhooksAirwallexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/exchange': typeof ExchangeRoute
  '/help': typeof HelpRoute
  '/mcp': typeof McpRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reverify': typeof ReverifyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/topup': typeof TopupRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/controls': typeof AdminControlsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/benefits/$id': typeof BenefitsIdRoute
  '/explore/admin': typeof ExploreAdminRoute
  '/explore/community': typeof ExploreCommunityRoute
  '/explore/events': typeof ExploreEventsRoute
  '/explore/food': typeof ExploreFoodRoute
  '/explore/health': typeof ExploreHealthRoute
  '/explore/housing': typeof ExploreHousingRoute
  '/explore/reserve': typeof ExploreReserveRoute
  '/explore/rides': typeof ExploreRidesRoute
  '/explore/shops': typeof ExploreShopsRoute
  '/explore/transit': typeof ExploreTransitRoute
  '/guides/$id': typeof GuidesIdRoute
  '/siddur/$id': typeof SiddurIdRoute
  '/admin': typeof AdminIndexRoute
  '/benefits': typeof BenefitsIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/siddur': typeof SiddurIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/explore/category/$id': typeof ExploreCategoryIdRoute
  '/explore/service/$id': typeof ExploreServiceIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/airwallex': typeof ApiPublicWebhooksAirwallexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/exchange': typeof ExchangeRoute
  '/help': typeof HelpRoute
  '/mcp': typeof McpRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reverify': typeof ReverifyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/terms': typeof TermsRoute
  '/topup': typeof TopupRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/controls': typeof AdminControlsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/benefits/$id': typeof BenefitsIdRoute
  '/explore/admin': typeof ExploreAdminRoute
  '/explore/community': typeof ExploreCommunityRoute
  '/explore/events': typeof ExploreEventsRoute
  '/explore/food': typeof ExploreFoodRoute
  '/explore/health': typeof ExploreHealthRoute
  '/explore/housing': typeof ExploreHousingRoute
  '/explore/reserve': typeof ExploreReserveRoute
  '/explore/rides': typeof ExploreRidesRoute
  '/explore/shops': typeof ExploreShopsRoute
  '/explore/transit': typeof ExploreTransitRoute
  '/guides/$id': typeof GuidesIdRoute
  '/siddur/$id': typeof SiddurIdRoute
  '/admin/': typeof AdminIndexRoute
  '/benefits/': typeof BenefitsIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/siddur/': typeof SiddurIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/explore/category/$id': typeof ExploreCategoryIdRoute
  '/explore/service/$id': typeof ExploreServiceIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/airwallex': typeof ApiPublicWebhooksAirwallexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/activity'
    | '/auth'
    | '/card'
    | '/exchange'
    | '/help'
    | '/mcp'
    | '/me'
    | '/membership'
    | '/news'
    | '/reset-password'
    | '/reverify'
    | '/settings'
    | '/sitemap.xml'
    | '/social'
    | '/terms'
    | '/topup'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/accounts'
    | '/admin/apps'
    | '/admin/controls'
    | '/admin/memberships'
    | '/admin/money'
    | '/admin/promotions'
    | '/benefits/$id'
    | '/explore/admin'
    | '/explore/community'
    | '/explore/events'
    | '/explore/food'
    | '/explore/health'
    | '/explore/housing'
    | '/explore/reserve'
    | '/explore/rides'
    | '/explore/shops'
    | '/explore/transit'
    | '/guides/$id'
    | '/siddur/$id'
    | '/admin/'
    | '/benefits/'
    | '/explore/'
    | '/guides/'
    | '/siddur/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/explore/category/$id'
    | '/explore/service/$id'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/airwallex'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/card'
    | '/exchange'
    | '/help'
    | '/mcp'
    | '/me'
    | '/membership'
    | '/news'
    | '/reset-password'
    | '/reverify'
    | '/settings'
    | '/sitemap.xml'
    | '/social'
    | '/terms'
    | '/topup'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/accounts'
    | '/admin/apps'
    | '/admin/controls'
    | '/admin/memberships'
    | '/admin/money'
    | '/admin/promotions'
    | '/benefits/$id'
    | '/explore/admin'
    | '/explore/community'
    | '/explore/events'
    | '/explore/food'
    | '/explore/health'
    | '/explore/housing'
    | '/explore/reserve'
    | '/explore/rides'
    | '/explore/shops'
    | '/explore/transit'
    | '/guides/$id'
    | '/siddur/$id'
    | '/admin'
    | '/benefits'
    | '/explore'
    | '/guides'
    | '/siddur'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/explore/category/$id'
    | '/explore/service/$id'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/airwallex'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/activity'
    | '/auth'
    | '/card'
    | '/exchange'
    | '/help'
    | '/mcp'
    | '/me'
    | '/membership'
    | '/news'
    | '/reset-password'
    | '/reverify'
    | '/settings'
    | '/sitemap.xml'
    | '/social'
    | '/terms'
    | '/topup'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/accounts'
    | '/admin/apps'
    | '/admin/controls'
    | '/admin/memberships'
    | '/admin/money'
    | '/admin/promotions'
    | '/benefits/$id'
    | '/explore/admin'
    | '/explore/community'
    | '/explore/events'
    | '/explore/food'
    | '/explore/health'
    | '/explore/housing'
    | '/explore/reserve'
    | '/explore/rides'
    | '/explore/shops'
    | '/explore/transit'
    | '/guides/$id'
    | '/siddur/$id'
    | '/admin/'
    | '/benefits/'
    | '/explore/'
    | '/guides/'
    | '/siddur/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/explore/category/$id'
    | '/explore/service/$id'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/airwallex'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  CardRoute: typeof CardRoute
  ExchangeRoute: typeof ExchangeRoute
  HelpRoute: typeof HelpRoute
  McpRoute: typeof McpRoute
  MeRoute: typeof MeRoute
  MembershipRoute: typeof MembershipRoute
  NewsRoute: typeof NewsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReverifyRoute: typeof ReverifyRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialRoute: typeof SocialRoute
  TermsRoute: typeof TermsRoute
  TopupRoute: typeof TopupRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BenefitsIdRoute: typeof BenefitsIdRoute
  ExploreAdminRoute: typeof ExploreAdminRoute
  ExploreCommunityRoute: typeof ExploreCommunityRoute
  ExploreEventsRoute: typeof ExploreEventsRoute
  ExploreFoodRoute: typeof ExploreFoodRoute
  ExploreHealthRoute: typeof ExploreHealthRoute
  ExploreHousingRoute: typeof ExploreHousingRoute
  ExploreReserveRoute: typeof ExploreReserveRoute
  ExploreRidesRoute: typeof ExploreRidesRoute
  ExploreShopsRoute: typeof ExploreShopsRoute
  ExploreTransitRoute: typeof ExploreTransitRoute
  GuidesIdRoute: typeof GuidesIdRoute
  SiddurIdRoute: typeof SiddurIdRoute
  BenefitsIndexRoute: typeof BenefitsIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  SiddurIndexRoute: typeof SiddurIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ExploreCategoryIdRoute: typeof ExploreCategoryIdRoute
  ExploreServiceIdRoute: typeof ExploreServiceIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWebhooksAirwallexRoute: typeof ApiPublicWebhooksAirwallexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverify': {
      id: '/reverify'
      path: '/reverify'
      fullPath: '/reverify'
      preLoaderRoute: typeof ReverifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siddur/': {
      id: '/siddur/'
      path: '/siddur'
      fullPath: '/siddur/'
      preLoaderRoute: typeof SiddurIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits/': {
      id: '/benefits/'
      path: '/benefits'
      fullPath: '/benefits/'
      preLoaderRoute: typeof BenefitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/siddur/$id': {
      id: '/siddur/$id'
      path: '/siddur/$id'
      fullPath: '/siddur/$id'
      preLoaderRoute: typeof SiddurIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$id': {
      id: '/guides/$id'
      path: '/guides/$id'
      fullPath: '/guides/$id'
      preLoaderRoute: typeof GuidesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/transit': {
      id: '/explore/transit'
      path: '/explore/transit'
      fullPath: '/explore/transit'
      preLoaderRoute: typeof ExploreTransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/shops': {
      id: '/explore/shops'
      path: '/explore/shops'
      fullPath: '/explore/shops'
      preLoaderRoute: typeof ExploreShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/rides': {
      id: '/explore/rides'
      path: '/explore/rides'
      fullPath: '/explore/rides'
      preLoaderRoute: typeof ExploreRidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/reserve': {
      id: '/explore/reserve'
      path: '/explore/reserve'
      fullPath: '/explore/reserve'
      preLoaderRoute: typeof ExploreReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/housing': {
      id: '/explore/housing'
      path: '/explore/housing'
      fullPath: '/explore/housing'
      preLoaderRoute: typeof ExploreHousingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/health': {
      id: '/explore/health'
      path: '/explore/health'
      fullPath: '/explore/health'
      preLoaderRoute: typeof ExploreHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/food': {
      id: '/explore/food'
      path: '/explore/food'
      fullPath: '/explore/food'
      preLoaderRoute: typeof ExploreFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/events': {
      id: '/explore/events'
      path: '/explore/events'
      fullPath: '/explore/events'
      preLoaderRoute: typeof ExploreEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/community': {
      id: '/explore/community'
      path: '/explore/community'
      fullPath: '/explore/community'
      preLoaderRoute: typeof ExploreCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/admin': {
      id: '/explore/admin'
      path: '/explore/admin'
      fullPath: '/explore/admin'
      preLoaderRoute: typeof ExploreAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits/$id': {
      id: '/benefits/$id'
      path: '/benefits/$id'
      fullPath: '/benefits/$id'
      preLoaderRoute: typeof BenefitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/money': {
      id: '/admin/money'
      path: '/money'
      fullPath: '/admin/money'
      preLoaderRoute: typeof AdminMoneyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/controls': {
      id: '/admin/controls'
      path: '/controls'
      fullPath: '/admin/controls'
      preLoaderRoute: typeof AdminControlsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/apps': {
      id: '/admin/apps'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AdminAppsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/service/$id': {
      id: '/explore/service/$id'
      path: '/explore/service/$id'
      fullPath: '/explore/service/$id'
      preLoaderRoute: typeof ExploreServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/category/$id': {
      id: '/explore/category/$id'
      path: '/explore/category/$id'
      fullPath: '/explore/category/$id'
      preLoaderRoute: typeof ExploreCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/airwallex': {
      id: '/api/public/webhooks/airwallex'
      path: '/api/public/webhooks/airwallex'
      fullPath: '/api/public/webhooks/airwallex'
      preLoaderRoute: typeof ApiPublicWebhooksAirwallexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAppsRoute: typeof AdminAppsRoute
  AdminControlsRoute: typeof AdminControlsRoute
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminMoneyRoute: typeof AdminMoneyRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAppsRoute: AdminAppsRoute,
  AdminControlsRoute: AdminControlsRoute,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminMoneyRoute: AdminMoneyRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  CardRoute: CardRoute,
  ExchangeRoute: ExchangeRoute,
  HelpRoute: HelpRoute,
  McpRoute: McpRoute,
  MeRoute: MeRoute,
  MembershipRoute: MembershipRoute,
  NewsRoute: NewsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReverifyRoute: ReverifyRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialRoute: SocialRoute,
  TermsRoute: TermsRoute,
  TopupRoute: TopupRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BenefitsIdRoute: BenefitsIdRoute,
  ExploreAdminRoute: ExploreAdminRoute,
  ExploreCommunityRoute: ExploreCommunityRoute,
  ExploreEventsRoute: ExploreEventsRoute,
  ExploreFoodRoute: ExploreFoodRoute,
  ExploreHealthRoute: ExploreHealthRoute,
  ExploreHousingRoute: ExploreHousingRoute,
  ExploreReserveRoute: ExploreReserveRoute,
  ExploreRidesRoute: ExploreRidesRoute,
  ExploreShopsRoute: ExploreShopsRoute,
  ExploreTransitRoute: ExploreTransitRoute,
  GuidesIdRoute: GuidesIdRoute,
  SiddurIdRoute: SiddurIdRoute,
  BenefitsIndexRoute: BenefitsIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  SiddurIndexRoute: SiddurIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ExploreCategoryIdRoute: ExploreCategoryIdRoute,
  ExploreServiceIdRoute: ExploreServiceIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWebhooksAirwallexRoute: ApiPublicWebhooksAirwallexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
